const products=[
{id:'p1',name:'پنیر محلی',weight:'۱ کیلوگرم',price:220000,oldPrice:280000,category:'محلی',icon:'🧀',image:'https://altmanassets.s3.amazonaws.com/uploads/2016/12/ThinkstockPhotos-154059593.jpg',tag:'ویژه',stock:18,description:'پنیر محلی تازه با طعم اصیل و بافت نرم.'},
{id:'p2',name:'دوغ تازه',weight:'۱.۵ کیلوگرم',price:96000,category:'نوشیدنی',icon:'🥛',image:'https://bazar-center.com/245695-large_default/%D9%83%D8%A7%D9%84%D8%A9_%D8%AF%D9%88%D8%BA_%D9%84%D8%A8%D9%86_%D8%A8%D8%B7%D9%84_%D8%A8%D9%84%D8%A7%D8%B3%D8%AA%D9%83_1_5_%D9%84%D8%AA%D8%B1__6.jpg',tag:'تازه',stock:24,description:'دوغ تازه و خنک با طعم سنتی.'},
{id:'p3',name:'ماست پرچرب',weight:'۱.۵ کیلوگرم',price:153000,category:'لبنیات',icon:'🥣',image:'https://www.highshop.ir/images/items/L10794.gif',tag:'پرفروش',stock:16,description:'ماست پرچرب با بافت غلیظ و طعم ملایم.'},
{id:'p4',name:'شیر محلی',weight:'۱ لیتر',price:76000,category:'لبنیات',icon:'🍼',image:'https://www.highshop.ir/images/items/L11010.gif',tag:'تازه',stock:30,description:'شیر محلی تازه برای مصرف روزانه.'},
{id:'p5',name:'خیارشور ویژه',weight:'۱ کیلوگرم',price:128000,category:'شورجات',icon:'🥒',image:'https://unbama.it/img/m/20263/42/%D8%AE%DB%8C%D8%A7%D8%B1%D8%B4%D9%88%D8%B1-%D8%AF%D8%B1%D8%AC%D9%87-1-%D8%B1%D8%A7%D8%B2%DA%A9-760-%DA%AF%D8%B1%D9%85.jpg?v=60683000',tag:'ویژه',stock:12,description:'خیارشور ترد و خوش‌طعم با مزه متعادل.'},
{id:'p6',name:'گوشت تازه',weight:'۱ کیلوگرم',price:540000,category:'پروتئین',icon:'🥩',image:'https://mir-s3-cdn-cf.behance.net/project_modules/fs/1630b214428759.56283c4199bf8.jpg',tag:'تازه',stock:9,description:'گوشت تازه با بسته‌بندی مناسب.'},
{id:'p7',name:'کشک محلی',weight:'۵۰۰ گرم',price:89000,category:'لبنیات',icon:'🥛',image:'https://fsn1.your-objectstorage.com/aradbranding-fa-uploads/topics/16752469226044.jpg',stock:20,description:'کشک محلی با طعم سنتی.'},
{id:'p8',name:'زیتون محلی',weight:'۵۰۰ گرم',price:165000,category:'محلی',icon:'🫒',image:'https://www.sorinaco.com/static/images/products/1/green_olive_Jars-1.png',stock:14,description:'زیتون محلی خوش‌طعم.'}
];
let activeCategory='همه';
const cartItems=new Map();
const grid=document.getElementById('productsGrid'),count=document.getElementById('cartCount'),bottomCount=document.getElementById('bottomCartCount'),input=document.getElementById('searchInput'),clear=document.getElementById('clearSearch'),searchWrap=document.querySelector('.search-wrap');
const status=document.createElement('div');status.className='search-status';status.setAttribute('aria-live','polite');searchWrap?.appendChild(status);
function normalize(v=''){return String(v).replace(/[يى]/g,'ی').replace(/ك/g,'ک').replace(/ۀ/g,'ه').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))).replace(/[\s\-_/]+/g,' ').trim().toLowerCase()}
function money(n){return n.toLocaleString('fa-IR')+' تومان'}
function matches(p,q){if(!q)return true;const h=normalize(p.name+' '+p.category+' '+p.weight+' '+(p.tag||'')+' '+p.description);return normalize(q).split(' ').filter(Boolean).every(w=>h.includes(w))}
function cartCount(){return [...cartItems.values()].reduce((s,x)=>s+x.qty,0)}
const CART_KEY='dastchin_cart_v2';
const savedCart=(()=>{try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch(e){return[]}})();
savedCart.forEach(x=>{const p=products.find(p=>p.id===x.id);if(p&&x.qty>0)cartItems.set(x.id,{product:p,qty:Math.min(p.stock,x.qty)})});
function persistCart(){localStorage.setItem(CART_KEY,JSON.stringify([...cartItems.values()].map(x=>({id:x.product.id,qty:x.qty}))))}
function syncCart(){const n=cartCount();if(count)count.textContent=n;if(bottomCount)bottomCount.textContent=n;const d=document.getElementById('drawerCartCount');if(d)d.textContent=n;persistCart();renderCart()}
function addToCart(id,qty=1){const p=products.find(x=>x.id===id);if(!p||p.stock<1)return;const item=cartItems.get(id)||{product:p,qty:0};item.qty=Math.min(p.stock,item.qty+qty);cartItems.set(id,item);syncCart()}
function changeQty(id,delta){const item=cartItems.get(id);if(!item)return;item.qty=Math.max(0,Math.min(item.product.stock,item.qty+delta));if(!item.qty)cartItems.delete(id);syncCart()}
function render(){
 const q=input?.value||'';const list=products.filter(p=>(activeCategory==='همه'||p.category===activeCategory)&&matches(p,q));
 grid.innerHTML=list.length?list.map(p=>'<article class="product"><button class="product-image-button" type="button" data-detail="'+p.id+'"><div class="product-img">'+(p.tag?'<span class="product-tag">'+p.tag+'</span>':'')+'<img class="product-photo" src="'+p.image+'" alt="'+p.name+'" loading="lazy"></div></button><div class="product-body"><button class="product-title-button" type="button" data-detail="'+p.id+'"><h3>'+p.name+'</h3><p>'+p.weight+'</p></button><div class="price-row"><div><div class="price">'+money(p.price)+'</div>'+(p.oldPrice?'<div class="old-price">'+money(p.oldPrice)+'</div>':'')+'</div><span class="product-stock">'+(p.stock?'موجود':'ناموجود')+'</span></div><button class="add" data-add="'+p.id+'" '+(!p.stock?'disabled':'')+'>'+ (p.stock?'افزودن به سبد':'ناموجود')+'</button></div></article>').join(''):'<div class="empty-state"><strong>محصولی پیدا نشد</strong><span>عبارت جستجو یا دسته‌بندی را تغییر بده.</span></div>';
 grid.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openProduct(products.find(p=>p.id===b.dataset.detail)));
 grid.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{addToCart(b.dataset.add);b.textContent='✓ به سبد اضافه شد';setTimeout(()=>b.textContent='افزودن به سبد',800)});
 status.textContent=q||activeCategory!=='همه'?list.length.toLocaleString('fa-IR')+' محصول نمایش داده شد'+(activeCategory!=='همه'?' · دسته: '+activeCategory:''):products.length.toLocaleString('fa-IR')+' محصول آماده نمایش است';
 if(clear)clear.style.display=q?'block':'none';
}
function openProduct(p){const m=document.getElementById('productModal');if(!m||!p)return;m.querySelector('[data-modal-icon]').innerHTML='<img class="modal-product-photo" src="'+p.image+'" alt="'+p.name+'">';m.querySelector('[data-modal-tag]').textContent=p.tag||'محصول دستچین';m.querySelector('[data-modal-name]').textContent=p.name;m.querySelector('[data-modal-weight]').textContent=p.weight;m.querySelector('[data-modal-description]').textContent=p.description;m.querySelector('[data-modal-price]').textContent=money(p.price);m.querySelector('[data-modal-old-price]').textContent=p.oldPrice?money(p.oldPrice):'';m.querySelector('[data-modal-stock]').textContent=p.stock?'موجود · '+p.stock.toLocaleString('fa-IR')+' عدد':'ناموجود';m.querySelector('[data-qty]').value=1;m.querySelector('[data-add-detail]').dataset.productId=p.id;m.classList.add('show');m.setAttribute('aria-hidden','false')}
function closeProduct(){const m=document.getElementById('productModal');if(m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}}
function renderCart(){const box=document.getElementById('cartItems'),totalEl=document.getElementById('cartTotal');if(!box)return;const items=[...cartItems.values()];box.innerHTML=items.length?items.map(x=>'<article class="cart-item"><img src="'+x.product.image+'" alt="'+x.product.name+'"><div><strong>'+x.product.name+'</strong><small>'+x.product.weight+'</small><b>'+money(x.product.price*x.qty)+'</b></div><div class="cart-item-actions"><button data-cart-minus="'+x.product.id+'">−</button><span>'+x.qty.toLocaleString('fa-IR')+'</span><button data-cart-plus="'+x.product.id+'">+</button><button class="cart-remove" data-cart-remove="'+x.product.id+'">حذف</button></div></article>').join(''):'<div class="cart-empty"><strong>سبد خرید خالی است</strong><span>محصولات موردنظرت را انتخاب کن.</span></div>';const total=items.reduce((s,x)=>s+x.product.price*x.qty,0);if(totalEl)totalEl.textContent=money(total);box.querySelectorAll('[data-cart-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.cartMinus,-1));box.querySelectorAll('[data-cart-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.cartPlus,1));box.querySelectorAll('[data-cart-remove]').forEach(b=>b.onclick=()=>{cartItems.delete(b.dataset.cartRemove);syncCart()})}
function openCart(){const m=document.getElementById('cartModal');if(m){renderCart();m.classList.add('show');m.setAttribute('aria-hidden','false')}}
function closeCart(){const m=document.getElementById('cartModal');if(m){m.classList.remove('show');m.setAttribute('aria-hidden','true')}}
document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.category||'همه';render();document.getElementById('products')?.scrollIntoView({behavior:'smooth',block:'start'})});
document.querySelectorAll('[data-menu-category]').forEach(a=>a.onclick=()=>{document.querySelector('.category[data-category="'+a.dataset.menuCategory+'"]')?.click()});
input?.addEventListener('input',render);clear?.addEventListener('click',()=>{input.value='';render();input.focus()});
document.querySelectorAll('a[href="#cart"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();closeDrawer();openCart()}));
document.addEventListener('click',e=>{const trigger=e.target.closest('a[href="#cart"],[data-open-cart]');if(trigger){e.preventDefault();e.stopPropagation();closeDrawer();openCart()}});
document.getElementById('cartModal')?.querySelector('[data-cart-close]')?.addEventListener('click',closeCart);document.getElementById('cartModal')?.querySelector('[data-cart-overlay]')?.addEventListener('click',closeCart);
document.getElementById('productModal')?.querySelector('[data-modal-close]')?.addEventListener('click',closeProduct);document.getElementById('productModal')?.querySelector('[data-modal-overlay]')?.addEventListener('click',closeProduct);
document.getElementById('productModal')?.querySelector('[data-qty-minus]')?.addEventListener('click',()=>{const q=document.querySelector('[data-qty]');q.value=Math.max(1,Number(q.value)-1)});
document.getElementById('productModal')?.querySelector('[data-qty-plus]')?.addEventListener('click',()=>{const m=document.getElementById('productModal'),p=products.find(x=>x.id===m.querySelector('[data-add-detail]').dataset.productId),q=m.querySelector('[data-qty]');q.value=Math.min(p.stock,Number(q.value)+1)});
document.getElementById('productModal')?.querySelector('[data-add-detail]')?.addEventListener('click',()=>{const m=document.getElementById('productModal'),p=products.find(x=>x.id===m.querySelector('[data-add-detail]').dataset.productId);addToCart(p.id,Number(m.querySelector('[data-qty]').value));closeProduct()});
const drawer=document.getElementById('drawer'),overlay=document.getElementById('overlay');function closeDrawer(){drawer?.classList.remove('open');overlay?.classList.remove('show');drawer?.setAttribute('aria-hidden','true')}document.getElementById('menuButton')?.addEventListener('click',()=>{drawer?.classList.add('open');overlay?.classList.add('show');drawer?.setAttribute('aria-hidden','false')});document.getElementById('drawerClose')?.addEventListener('click',closeDrawer);overlay?.addEventListener('click',closeDrawer);document.querySelectorAll('.drawer a').forEach(a=>a.addEventListener('click',closeDrawer));
(function(){const c=document.querySelector('.cart-action>span');if(c)c.innerHTML='<svg class="cart-svg" viewBox="0 0 48 48"><path d="M7 9h5l4.2 22.5h21.6L42 16H13.2"></path><circle cx="20" cy="38" r="2.8"></circle><circle cx="35" cy="38" r="2.8"></circle></svg>';const a=document.querySelector('.round-action .account-icon');if(a)a.innerHTML='<svg class="account-svg" viewBox="0 0 48 48"><circle cx="24" cy="14.5" r="7.2"></circle><path d="M11 38.5c1.7-7.2 6.3-11 13-11s11.3 3.8 13 11"></path></svg>'})();
render();syncCart();