(function(){
'use strict';
var S='a[href="#cart"],[data-open-cart],.cart-action,.cart-icon,[data-cart-open]';
function el(id){return document.getElementById(id)}
function render(){try{if(typeof window.renderCart==='function')window.renderCart()}catch(e){console.error('[cart]',e)}}
function open(e){if(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation&&e.stopImmediatePropagation()}var m=el('cartModal');if(!m)return false;render();m.classList.add('show');m.setAttribute('aria-hidden','false');m.style.setProperty('display','block','important');m.style.setProperty('visibility','visible','important');m.style.setProperty('opacity','1','important');m.style.setProperty('pointer-events','auto','important');m.style.setProperty('z-index','2147483647','important');document.body.classList.add('cart-open');document.body.style.overflow='hidden';return false}
function close(e){if(e){e.preventDefault();e.stopPropagation()}var m=el('cartModal');if(!m)return;m.classList.remove('show');m.setAttribute('aria-hidden','true');m.style.setProperty('display','none','important');m.style.setProperty('visibility','hidden','important');m.style.setProperty('opacity','0','important');m.style.setProperty('pointer-events','none','important');document.body.classList.remove('cart-open');document.body.style.overflow=''}
function checkout(){var items=window.__dastchinCartItems?window.__dastchinCartItems():[];if(!items.length){alert('سبد خرید خالی است');return}var old=el('checkoutModal');if(old)old.remove();var total=items.reduce(function(s,x){return s+x.product.price*x.qty},0);var m=document.createElement('div');m.id='checkoutModal';m.className='checkout-modal';m.innerHTML='<div class="checkout-overlay" data-checkout-close></div><div class="checkout-panel" role="dialog" aria-modal="true"><div class="checkout-head"><div><h2>نهایی کردن سفارش</h2><small>اطلاعات ارسال و پرداخت</small></div><button type="button" data-checkout-close>×</button></div><form id="checkoutForm"><label>نام و نام خانوادگی<input name="name" required autocomplete="name"></label><label>شماره موبایل<input name="phone" required inputmode="tel" pattern="[0-9۰-۹+ -]{10,}" autocomplete="tel"></label><label>آدرس کامل<input name="address" required autocomplete="street-address"></label><div class="checkout-row"><label>روش ارسال<select name="shipping"><option value="پیک دستچین">پیک دستچین</option><option value="ارسال عادی">ارسال عادی</option></select></label><label>روش پرداخت<select name="payment"><option value="پرداخت آنلاین">پرداخت آنلاین</option><option value="پرداخت هنگام تحویل">پرداخت هنگام تحویل</option></select></label></div><div class="checkout-total"><span>مبلغ قابل پرداخت</span><strong>'+money(total)+'</strong></div><button class="checkout-submit" type="submit">ثبت و ادامه پرداخت</button><p class="checkout-note">در این نسخه، اتصال واقعی به درگاه بانکی هنوز در سمت سرور تعریف نشده است؛ اطلاعات سفارش در مرورگر ذخیره می‌شود.</p></form></div>';document.body.appendChild(m);m.querySelectorAll('[data-checkout-close]').forEach(function(b){b.addEventListener('click',function(){m.remove();document.body.style.overflow='hidden'})});m.querySelector('form').addEventListener('submit',function(e){e.preventDefault();var f=new FormData(e.currentTarget);var order={id:'DC-'+Date.now(),createdAt:new Date().toISOString(),customer:Object.fromEntries(f.entries()),items:items.map(function(x){return{id:x.product.id,name:x.product.name,qty:x.qty,price:x.product.price}}),total:total,status:'ثبت اولیه'};localStorage.setItem('dastchin_last_order',JSON.stringify(order));m.querySelector('.checkout-panel').innerHTML='<div class="order-success"><div>✓</div><h2>سفارش ثبت شد</h2><p>شماره سفارش: <strong>'+order.id+'</strong></p><p>سفارش شما برای ادامه فرایند آماده است.</p><button type="button" class="checkout-submit" id="finishOrder">بازگشت به فروشگاه</button></div>';var cart=el('cartModal');if(cart)cart.classList.remove('show');if(window.__dastchinClearCart)window.__dastchinClearCart();m.querySelector('#finishOrder').onclick=function(){m.remove();document.body.style.overflow='';}})}
function money(n){return Number(n).toLocaleString('fa-IR')+' تومان'}
function bind(){document.addEventListener('click',function(e){var t=e.target.closest&&e.target.closest(S);if(t){open(e);return}if(e.target.closest&&e.target.closest('[data-cart-close],[data-cart-overlay]')){close(e);return}if(e.target.closest&&e.target.closest('.checkout-btn')){e.preventDefault();e.stopImmediatePropagation();checkout();return}},true);document.addEventListener('keydown',function(e){if(e.key==='Escape'){close();var c=el('checkoutModal');if(c)c.remove()}});window.openDastchinCart=open;window.openCart=open;window.closeDastchinCart=close;window.closeCart=close;window.__dastchinCartItems=function(){try{return window.__dastchinGetCartItems?window.__dastchinGetCartItems():[]}catch(e){return[]}};window.__dastchinClearCart=function(){try{if(window.__dastchinClearCartInternal)window.__dastchinClearCartInternal()}catch(e){}};var m=el('cartModal');if(m){m.style.display='none';m.setAttribute('aria-hidden','true')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();